name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
         dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: CICDSampleAPI/CICDSampleAPI
    - name: Build
      working-directory: CICDSampleAPI/CICDSampleAPI
      run: dotnet build --no-restore
    - name: Test
      working-directory: CICDSampleAPI/CICDSampleAPI
      run: dotnet test --no-build --verbosity normal      
    - name: Add remote origin
      uses: netlify/actions/cli@master #uses Netlify Cli actions
      env: # These are the environment variables added in GitHub Secrets for this repo
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_APP_ID }}
      with:
          args: deploy --dir=publishoutput/wwwroot --prod #push this folder to Netlify
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_APP_ID"]' 
