name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
         dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: CICDSampleAPI/CICDSampleAPI
    - name: Build
      working-directory: CICDSampleAPI/CICDSampleAPI
      run: dotnet build --no-restore
    - name: Test
      working-directory: CICDSampleAPI/CICDSampleAPI
      run: dotnet test --no-build --verbosity normal
    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/hrhlistetest.git
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f
